import { windowHeight } from "@/utils/utils"
import { windowWidth } from "@api/api"
import sColor from "@styles/color"
import { PixelRatio, StyleSheet } from "react-native"
export default StyleSheet.create({
  loading: {
    width: windowWidth,
    height: windowHeight,
    backgroundColor: sColor.white,
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  loadingTitle: {
    textAlign: "center",
    justifyContent: "center",
  },
  loadingPic: {
    width: "100%",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  loadingImg: {
    width: 300,
    resizeMode: "center",
  },
  edit: {
    flex: 1,
  },
  main: {
    flex: 0.9,
    backgroundColor: sColor.mainBgColor,
  },
  header: {
    padding: 15,
    backgroundColor: sColor.mainRed,
  },
  headerInfo: {},
  headerInfoAvatar: {
    width: 45,
    height: 45,
    borderRadius: 100,
    overflow: "hidden",
  },
  headerInfoImg: {
    width: 45,
    height: 45,
    resizeMode: "cover",
  },
  headerInfoName: {
    marginLeft: 15,
    flex: 1,
  },
  headerInfoTitle: {
    color: sColor.white,
    fontWeight: "500",
    marginBottom: 5,
  },
  headerInfoDetail: {
    color: sColor.white,
  },
  headerInfoCustomer: {
    height: 30,
    paddingLeft: 15,
    paddingRight: 15,
    lineHeight: 30,
    borderRadius: 25,
    borderWidth: 1 / PixelRatio.get(),
    borderColor: sColor.white,
    color: sColor.white,
  },
  headerDescription: {
    marginTop: 5,
  },
  headerDepartment: {
    color: sColor.white,
    marginTop: 10,
  },
  department: {
    paddingLeft: 15,
    paddingRight: 15,
    marginTop: 30,
    marginBottom: 30,
  },
  departmentTitle: {
    color: sColor.mainBlack,
  },
  departmentEdit: {
    color: sColor.color888,
  },
  departmentList: {
    paddingTop: 12,
  },
  departmentItem: {
    marginRight: 15,
    marginBottom: 15,
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 2,
    borderWidth: 1 / PixelRatio.get(),
    borderColor: sColor.color999,
    color: sColor.color666,
  },
  profile: {
    paddingLeft: 15,
    paddingRight: 15,
    paddingBottom: 30,
  },
  profileTitle: {
    marginBottom: 15,
  },
  profileTheme: {
    color: sColor.mainBlack,
  },
  profileEdit: {
    color: sColor.color888,
  },
  profileDetail: {
    color: sColor.color666,
    lineHeight: 25,
  },
  viewFa: {
    flex: 0.1,
    height: 50,
    paddingRight: 5,
    paddingLeft: 5,
    paddingTop: 5,
    paddingBottom: 5,
    backgroundColor: sColor.mainBgColor,
    borderTopColor: sColor.colorDdd,
    borderTopWidth: 1 / PixelRatio.get(),
  },
  view: {
    height: 45,
    lineHeight: 45,
    textAlign: "center",
    color: sColor.white,
    backgroundColor: sColor.mainRed,
    borderRadius: 5,
  },
  selectDepartment: {
    position: "absolute",
    top: 0,
    right: 0,
    left: 0,
    bottom: 0,
    backgroundColor: sColor.white,
  },
  closeDepartment: {
    height: 45,
    lineHeight: 45,
    textAlign: "center",
    color: sColor.white,
    backgroundColor: sColor.color666,
  },
  selectDepartmentList: {
    backgroundColor: sColor.white,
    paddingLeft: 15,
    paddingRight: 15,
    paddingTop: 15,
    paddingBottom: 15,
  },
  selectDepartmentTitle: {
    height: 45,
    backgroundColor: sColor.white,
    borderBottomWidth: 1 / PixelRatio.get(),
    borderBottomColor: sColor.colorDdd,
  },
  selectDepartmentIcon: {
    width: 5,
    height: 25,
    backgroundColor: sColor.mainRed,
  },
  selectDepartmentTheme: {
    color: sColor.color333,
    marginLeft: 15,
    marginRight: 15,
  },
  selectDepartmentDetail: {
    color: sColor.color888,
  },
  selectDepartmentItem: {
    height: 35,
    paddingLeft: 15,
    paddingRight: 15,
    lineHeight: 35,
    color: sColor.color666,
    borderWidth: 1 / PixelRatio.get(),
    borderColor: sColor.colorDdd,
    borderRadius: 2,
    marginRight: 15,
    marginBottom: 15,
  },
  selectDepartmentItemActive: {
    color: sColor.white,
    backgroundColor: sColor.mainRed,
    borderColor: sColor.mainRed,
    height: 35,
    paddingLeft: 15,
    paddingRight: 15,
    lineHeight: 35,
    borderWidth: 1 / PixelRatio.get(),
    borderRadius: 2,
    marginRight: 15,
    marginBottom: 15,
  },
  editProfile: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: sColor.white,
  },
  editProfileInput: {
    fontSize: 14,
    color: sColor.color666,
  },
  editProfileBtn: {
    height: 45,
    lineHeight: 45,
    textAlign: "center",
    backgroundColor: sColor.mainRed,
    color: sColor.white,
    marginTop: 30,
    marginLeft: 15,
    marginRight: 15,
    borderRadius: 5,
  },
  editInput: {
    paddingLeft: 15,
    paddingRight: 15,
  },
})
