import { StyleSheet, PixelRatio } from 'react-native';
import { windowWidth } from '../utils/utils';

export default StyleSheet.create({
    index: {
        backgroundColor: "#e9e9e9",
    },
    banner: {},
    linearGradient: {
        height: 40,
        justifyContent: 'center',
        flex: 1,
    },
    headerText: {
        color: "#fff",
        fontSize: 14,
        textAlign: 'center',
    },
    wrapper: {
        height: 130,
    },
    bannerBox: {
        flex: 1,
        justifyContent: "center",
        alignContent: "center",
    },
    bannerImg: {
        flex: 1,
        width: windowWidth,
        height: 130,
    },
    hidden: {
        display: "none",
    },
    verified: {
        height: 40,
        backgroundColor: '#feeae3',
        justifyContent: "flex-start",
        alignItems: 'center',
        flexDirection: 'row',
        paddingLeft: 10,
        paddingRight: 10,
    },
    verifiedImg: {
        width: 18,
        height: 18,
        resizeMode: 'center',
        marginRight: 5,
    },
    verifiedTitle: {
        fontSize: 14,
        color: "#e92b32",
    },
    verifiedIcon: {
        position: 'absolute',
        right: 10,
    },
    orderList: {
        flexDirection: "row",
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingLeft: 20,
        paddingRight: 20,
        paddingTop: 10,
        paddingBottom: 10,
        height: 100,
        backgroundColor: "#f5f5f5",
    },
    orderItem: {
        flex: 1,
        justifyContent: "center",
        alignItems: 'center',
    },
    orderItemImg: {
        width: 55,
        height: 55,
    },
    orderItemTitle: {
        fontSize: 14,
        color: "#6e6e6e",
        marginTop: 10,
    },
    center: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 5,
        backgroundColor: "#f5f5f5",
        flexDirection: "row",
        height: 60,
    },
    centerItem: {
        width: 180,
        justifyContent: 'center',
        alignItems: 'center',
        height: 50,
    },
    centerImg: {
        position: 'absolute',
        top: 10,
        right: 30,
        width: 42,
        height: 42,
        resizeMode: 'center',
        display: 'none',
    },
    centerTitle: {
        width: 90,
        height: 25,
        lineHeight: 25,
        textAlign: 'center',
        borderWidth: 1 / PixelRatio.get(),
        borderRadius: 25,
        borderColor: "#f53f68",
        color: '#f53f68',
        fontSize: 14,
    },
    centerBorderRight: {
        borderRightWidth: 1 / PixelRatio.get(),
        borderColor: '#f53f68',
    },
    add: {
        height: 85,
        marginTop: 5,
        backgroundColor: '#f5f5f5',
        paddingLeft: 20,
        paddingRight: 20,
        justifyContent: 'center',
        alignContent: 'center',
        paddingBottom: 5,
    },
    addImg: {
        resizeMode: 'center',
        height: 72,
    },
    addTitle: {
        textAlign: "center",
        fontSize: 16,
        color: '#fff',
        marginTop: 15,
        marginRight: 75,
    },
    addNum: {
        fontSize: 16,
        color: '#fff',
        textAlign: 'center',
        marginRight: 75,
    },
    detail: {
        fontSize: 18,
        color: '#fff',
    },
    resource: {
        marginTop: 5,
        backgroundColor: "#f5f5f5",
    },
    resourceTheme: {
        height: 30,
        lineHeight: 30,
        fontSize: 14,
        color: "#9f9f9f",
        paddingLeft: 15,
        marginBottom: 5,
    },
    resourceList: {
        flex: 1,
        justifyContent: 'center',
        alignItems: "center",
    },
    resourceItem: {
        width: windowWidth - 30,
        height: 45,
        backgroundColor: "#fff",
        marginBottom: 15,
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingLeft: 10,
        paddingRight: 15,
    },
    left: {
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    resourceImg: {
        width: 20,
        height: 20,
        resizeMode: 'contain',
    },
    resourceTitle: {
        fontSize: 14,
        color: "#9f9f9f",
        marginLeft: 10,
    },
    right: {
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    resourceDetail: {
        fontSize: 12,
        color: "#9f9f9f",
        marginLeft: 10,
    },
    caseNumber: {
        marginBottom: 15,
    },
    caseNumberDescription: {
        fontSize: 10,
        color: "#ccc",
    },
});
