import { StyleSheet, PixelRatio } from 'react-native'
import sColor from '@styles/color'
import { windowWidth } from '@api/api'
import { windowHeight } from '@/utils/utils'
export default StyleSheet.create({
  loading: {
    width: windowWidth,
    height: windowHeight,
    backgroundColor: sColor.white,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  loadingTitle: {
    textAlign: 'center',
    justifyContent: 'center',
  },
  loadingPic: {
    width: '100%',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingImg: {
    width: 300,
    resizeMode: 'contain',
  },
  main: {
    flex: 1,
    backgroundColor: sColor.mainBgColor,
  },
  header: {
    height: 45,
    backgroundColor: sColor.white,
    marginBottom: 8,
  },
  headerItem: {
    width: windowWidth / 3,
    textAlign: 'center',
    color: sColor.color333,
  },
  headerItemDisabled: {
    width: windowWidth / 3,
    textAlign: 'center',
    color: sColor.color999,
  },
  headerLine: {
    width: 1 / PixelRatio.get(),
    height: 25,
    backgroundColor: sColor.colorDdd,
  },
  headerLeft: {
    paddingLeft: 15,
    paddingRight: 30,
    paddingTop: 5,
    paddingBottom: 5,
    color: sColor.color666,
  },
  list: {
    backgroundColor: sColor.white,
    minHeight: windowHeight - 150,
  },
  theme: {
    height: 50,
    lineHeight: 50,
    textAlign: 'center',
    color: sColor.color333,
    borderBottomWidth: 1 / PixelRatio.get(),
    borderBottomColor: sColor.colorDdd,
    backgroundColor: sColor.white,
  },
  littleSpot: {
    marginLeft: 2,
    marginRight: 2,
    width: 2,
    height: 2,
    borderRadius: 100,
    backgroundColor: sColor.color333,
  },
  item: {
    paddingLeft: 20,
    paddingRight: 20,
    // paddingTop: 5,
    // width: 150,
    backgroundColor: '#f9f9f9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  numberRight: {
    paddingRight: 10,
  },
  wid: {
    width: 50,
    textAlign: "right",
  },
  itemWest: {
    padding: 15,
    paddingTop: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 1 / PixelRatio.get(),
    borderBottomColor: sColor.colorEee,
  },
  itemIcon: {
    color: sColor.mainRed,
    marginRight: 10,
  },
  itemCenter: {
    flex: 1,
    marginRight: 15,
  },
  flex: {
    display: 'flex',
    flexDirection: 'row',
  },
  itemCenterTitleFa: {
    height: 20,
  },
  itemCenterTitlePar: {
    height: 20,
  },
  itemCenterTitle: {
    lineHeight: 32,
    marginRight: 5,
  },
  deficiency: {
    color: sColor.mainRed,
  },
  itemNumber: {color: sColor.mainRed,},
  itemCenterDetail: {marginRight: 5,},
  itemCenterDetailTitle: {
    marginTop: 5,
    color: sColor.color666,
  },
  itemCenterDetailCompany: {
    color: sColor.color888,
  },
  stepper: {},
  stepperInput: {
    fontSize: 14,
    color: sColor.color666,
  },
  input: {
    fontSize: 14,
    color: sColor.color666,
  },
  inputWrap: {
    width: windowWidth / 2,
    height: 30,
    flex: 1,
  },
  closeList: {
    color: sColor.color666,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: 60,
    marginRight: 20,
  },
  closeBtn: {
    fontSize: 24,
  },
  searchIcon: {
    color: '#999',
    fontSize: 14,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 100,
    padding: 5,
    textAlign: 'center',
  },
  drugList: {
    padding: 15,
    backgroundColor: sColor.white,
  },
  drugItem: {
    marginLeft: 15,
    marginRight: 15,
    paddingTop: 15,
    paddingBottom: 15,
    borderBottomWidth: 1 / PixelRatio.get(),
    borderBottomColor: sColor.colorEee,
  },
  drugTitle: {
    color: sColor.color333,
    marginBottom: 5,
  },
  drugDetail: {},
  drugDescription: {
    color: sColor.color666,
    marginTop: 5,
  },
  drugCompany: {
    color: sColor.color999,
    marginTop: 5,
  },
  setCount: {
    width: 130,
  },
  btn: {
    width: 35,
    height: 25,
    borderRadius: 5,
    borderWidth: 1 / PixelRatio.get(),
    borderColor: sColor.colorDdd,
    lineHeight: 25,
    textAlign: 'center',
  },
  count: {
    width: 70,
    margin: 0,
    padding: 0,
    color: sColor.color666,
    textAlign: 'center',
    borderBottomWidth: 1 / PixelRatio.get(),
    borderBottomColor: sColor.colorDdd,
  },
  popularDrug: {
    padding: 15,
  },
  popularDrugList: {},
  popularDrugItem: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    marginBottom: 10,
    marginRight: 10,
  },
  drugItemTitle: {
    padding: 6,
    paddingLeft: 16,
    paddingRight: 16,
  },
  modal: {
    position: 'absolute',
    paddingTop: 25,
    paddingBottom: 0,
    paddingRight: 0,
    paddingLeft: 0,
    top: 100,
    width: '86%',
    left: '7%',
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  inputDrug: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
  },
  // inputWrap: {
  //   flex: 1,
  // },
  inputNum: {
    borderBottomWidth: 1,
    borderBottomColor: '#333',
    color: sColor.color666,
    fontSize: 14,
    width: 200,
    textAlign: 'center',
  },
  addDrugFive: {
    fontSize: 14,
    marginLeft: 10,
    marginRight: 10,
    width: 20,
  },
  chooseList: {
    marginTop: 20,
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  chooseItem: {
    fontSize: 14,
    borderWidth: 1,
    borderColor: '#ccc',
    paddingTop: 5,
    paddingBottom: 5,
    paddingRight: 10,
    paddingLeft: 10,
  },
  activeChooseItem: {
    fontSize: 14,
    borderWidth: 1,
    borderColor: sColor.mainRed,
    paddingTop: 5,
    paddingBottom: 5,
    paddingRight: 10,
    paddingLeft: 10,
  },
})
