import { StyleSheet, PixelRatio } from "react-native";
import { windowHeight, windowWidth } from '../../utils/utils';

export default StyleSheet.create({
    main: {
        marginBottom: 40,
    },
    banner: {
        backgroundColor: "#fff",
        width: windowWidth,
        flex: 1,
        height: windowWidth / 750 * 452,
        justifyContent: "center",
        alignItems: "center",
    },
    bannerImg: {
        resizeMode: 'contain',
        width: windowWidth,
        flex: 1,
    },
    hidden: {
        display: "none",
    },
    registerSelect: {
        flexDirection: 'row',
        justifyContent: "center",
        alignItems: 'center',
        height: 50,
        borderBottomColor: "#f5f5f5",
        borderBottomWidth: 1 / PixelRatio.get(),
    },
    registerSelectTitle: {
        fontSize: 14,
        color: "#f53f68",
        height: 50,
        lineHeight: 50,
        textAlign: "center",
        width: 100,
        justifyContent: 'center',
        alignItems: 'center',
    },
    registerSelecActive: {
        borderBottomColor: "#f53f68",
        borderBottomWidth: 3,
        color: "#f53f68",
    },
    inputBox: {
        flex: 1,
        justifyContent: 'center',
        marginBottom: 10,
        marginTop: 10,
        height: 50,
    },
    inputBoxImg: {
        position: 'absolute',
        maxWidth: 20,
        maxHeight: 20,
        left: 20,
        zIndex: 10,
        resizeMode: 'center',
    },
    InputItem: {
        flex: 1,
        justifyContent: 'flex-start',
        alignItems: 'center',
        flexDirection: 'row',
        height: 50,
        backgroundColor: "#f4f4f4",
        borderRadius: 5,
        fontSize: 14,
        color: "#bfbfbf",
        paddingLeft: 40,
        marginLeft: 10,
        marginRight: 10,
    },
    btn: {
        marginLeft: 10,
        marginRight: 10,
        height: 40,
        borderRadius: 5,
        marginTop: 10,
    },
    btnTitle: {
        fontSize: 14,
        color: "#fff",
        height: 40,
        lineHeight: 40,
        textAlign: 'center',
    },
    bottom: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginLeft: 10,
        marginRight: 10,
        marginTop: 10,
    },
    bottomTitle: {
        fontSize: 14,
        color: "#f53f68",
    },
    codeBox: {
        width: 100,
        height: 30,
        borderRadius: 25,
        position: 'absolute',
        right: 20,
        top: 10,
        zIndex: 10,
        justifyContent: 'center',

    },
    codeTitle: {
        fontSize: 12,
        color: "#fff",
        width: 100,
        height: 30,
        textAlign: 'center',
        lineHeight: 30,
    },
    agree: {
        flexDirection: 'row',
        justifyContent: "center",
        alignItems: 'center',
        marginBottom: 10,
        marginTop: 10,
    },
    agreeImg: {
        width: 13,
        height: 13,
        resizeMode: "center",
        marginRight: 5,
    },
    agreeTtitle: {
        fontSize: 12,
        color: "#a5a5a5",
    },


})
