export const BASE_URL = "https://www.byhealth.net"
export const CDN_BASE_URL = "https://cdn.byhealth.net/boyi"
export const WSS_URL = "wss://www.byhealth.net/sw"
export const customerServicePhone = "4000566629"
export const customerServiceWeChat = "byhealth001"
export { default as registerAgreementHtml } from "./registerAgreement"
