export default {
  common: {
    home: require("@img/common/home.png"),
    homeActive: require("@img/common/home_active.png"),
    personalCenter: require("@img/common/personal.png"),
    personalCenterActive: require("@img/common/personal_active.png"),
    addressBook: require("@img/common/address_book.png"),
    addressBookActive: require("@img/common/address_book_active.png"),
    advisory: require("@img/common/advisory.png"),
    advisoryActive: require("@img/common/advisory_active.png"),
    defaultAvatar: require("@img/common/default_avatar.jpg"),
    logo: require("@img/common/logo.png"),
    man: require("@img/common/man.png"),
    woman: require("@img/common/woman.png"),
    genderNull: require("@img/common/gender_null.png"),
    defaultPic: require("@img/common/default_pic.png"),
    technicalqualificationCertificatePicFirst: require("@img/common/technicalqualificationCertificatePicFirst.png"),
    technicalqualificationCertificatePicSecond: require("@img/common/technicalqualificationCertificatePicSecond.png"),
    loading: require("@img/common/loadding.gif"),
    flag: require("@img/common/flag.png"),
    injury: require("@img/common/injury.jpg"),
  },
  home: {
    prescriptionTemplate: require("@img/home/moban.png"),
    uploadPrescription: require("@img/home/shangchuan.png"),
    sittingInformation: require("@img/home/xinxi.png"),
    prescriptionTpl: require("@img/home/moban.png"),
    select: require("@img/home/xuanze.png"),
    invite: require("@img/home/yaoqing.png"),
    banner_0: require("@img/home/banner_0.jpg"),
    banner_1: require("@img/home/banner_1.jpg"),
    banner_2: require("@img/home/banner_2.jpg"),
    banner_3: require("@img/home/banner_3.jpg"),
    empty: require("@img/home/empty.png"),
  },
  advisory: {
    pillPurchase: require("@img/advisory/pill_purchase.png"),
    reply: require("@img/advisory/reply.png"),
    followUp: require("@img/advisory/follow_up.png"),
    closingConversation: require("@img/advisory/closing-conversation.png"),
    dialecticalPrescriptions: require("@img/advisory/dialectical-prescriptions.png"),
    givingquestions: require("@img/advisory/giving-questions.png"),
    inquirySheet: require("@img/advisory/inquiry-sheet.png"),
    picture: require("@img/advisory/picture.png"),
    quickReply: require("@img/advisory/quick-reply.png"),
    retract: require("@img/advisory/retract.png"),
    sittingInformation: require("@img/advisory/sitting-information.png"),
    show: require("@img/advisory/show.png"),
    selectPic: require("@img/advisory/select-pic.png"),
    selectPhoto: require("@img/advisory/select-photo.png"),
    voice: require("@img/advisory/voice.png"),
    customerServicePhone: require("@img/advisory/customer-service-phone.png"),
    customerServiceQQ: require("@img/advisory/customer-service-qq.png"),
    customerServiceWeixin: require("@img/advisory/customer-service-weixin.png"),
    aboutWeixin: require("@img/advisory/customer-service-weixin.png"),
  },
  addressBook: {
    group: require("@img/address_book/group.png"),
    phone: require("@img/address_book/phone.png"),
  },
  personalCenter: {},
}
